import { writeFile } from "node:fs/promises";
import type { Locator, Page, TestInfo } from "@playwright/test";
import { test, expect } from "./fixtures";
import { configuration } from "../fixtures/configuration";
import { en } from "../../src/shared/i18n/en";
import { zhCN } from "../../src/shared/i18n/zh-CN";

const path="/v1/routing/configuration";
const layout={version:1 as const,nodes:{questions:{x:50,y:80},"rule-0":{x:420,y:80},fallback:{x:420,y:300}},viewport:{x:0,y:0}};
async function frames(page:Page){await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));}
async function bounds(target:Locator){return target.evaluate(el=>{const b=el.getBoundingClientRect(),y=el.hasAttribute("data-canvas-node")?b.top+18:b.top+b.height/2;return{rect:b.toJSON(),focused:el===document.activeElement,visibleFocus:el.matches(":focus-visible"),hits:[b.left+2,b.left+b.width/2,b.right-2].map(x=>el.contains(document.elementFromPoint(x,y))),disabled:el.matches(":disabled")};});}
async function tab(page:Page,target:Locator){await frames(page);await expect(target).toBeEnabled();for(let n=0;n<120&&!(await target.evaluate(el=>el===document.activeElement));n++){await expect(target).toBeEnabled();await page.keyboard.press("Tab");await frames(page);}await expect(target).toBeFocused();const b=await bounds(target);expect(b.visibleFocus).toBe(true);expect(b.hits.every(Boolean),JSON.stringify(b)).toBe(true);return b;}
async function capture(page:Page,info:TestInfo,name:string,data:unknown){await writeFile(info.outputPath(name+".json"),JSON.stringify(data,null,2));await page.screenshot({path:info.outputPath(name+".png")});}
async function open(page:Page,locale:"en"|"zh-CN",width:number,scheme:"light"|"dark"){await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:scheme,reducedMotion:"reduce"});await page.goto("/dashboard/");if(locale==="zh-CN"){await page.getByRole("button",{name:en.settings,exact:true}).click();await page.locator("[data-settings-language]").selectOption(locale);}const words=locale==="en"?en:zhCN;await page.getByRole("button",{name:words.strategyEditor,exact:true}).click();await expect(page.getByRole("button",{name:words.canvasAddNode,exact:true})).toBeEnabled();return words;}

for(const [locale,width,scheme] of [["en",1280,"light"],["zh-CN",320,"dark"]] as const)test(`native Tab Enter admits known reset retry ${locale} ${width} ${scheme}`,async({page,mockApi},info)=>{
  mockApi.canvasLayout=structuredClone(layout);mockApi.appliedConfiguration={...structuredClone(configuration),config_hash:"wave4-known",fallback:{label:"quality"}};mockApi.allowedWrites.push({method:"DELETE",path});
  const requests:{method:string;path:string}[]=[];page.on("request",r=>requests.push({method:r.method(),path:new URL(r.url()).pathname}));let deletes=0;
  await page.route(`**${path}`,async route=>{if(route.request().method()==="DELETE"&&++deletes===1)return route.fulfill({status:503,json:{error:{message:"Wave4 known rejection"}}});return route.fallback();});
  const words=await open(page,locale,width,scheme);await page.locator('[data-canvas-node="questions"]').click();const inspector=page.getByRole("complementary",{name:words.nodeInspector}),field=inspector.getByRole("textbox",{name:words.instructions,exact:true}),raw="Native retry preserves 原始 draft";await field.fill(raw);
  await tab(page,page.getByRole("button",{name:words.closeInspector,exact:true}));await page.keyboard.press("Enter");
  const baseline=page.getByRole("button",{name:words.resetBaseline,exact:true});const entry=await tab(page,baseline);await expect(page.getByRole("button",{name:words.settings,exact:true})).toBeEnabled();const saved=structuredClone(mockApi.canvasLayout);await capture(page,info,"before-native-reset",{entry,saved,requests});await page.keyboard.press("Enter");
  const confirm=page.getByRole("button",{name:words.confirmReset,exact:true});const first=await tab(page,confirm);await page.keyboard.press("Enter");await expect.poll(()=>deletes).toBe(1);await expect(page.getByRole("alert")).toContainText("Wave4 known rejection");await expect(confirm).toBeEnabled();await expect(page.getByRole("button",{name:words.routingRetryRead,exact:true})).toHaveCount(0);await capture(page,info,"known-rejection",{first,deletes,requests,truth:mockApi.appliedConfiguration});
  await tab(page,page.getByRole("button",{name:words.backToEditing,exact:true}));await page.keyboard.press("Enter");await expect(page.getByRole("button",{name:words.canvasUndo,exact:true})).toBeEnabled();await tab(page,baseline);await page.keyboard.press("Enter");
  const retry=await tab(page,confirm);await capture(page,info,"native-retry-ready",{retry,deletes,requests});await page.keyboard.press("Enter");await expect.poll(()=>deletes).toBe(2);await capture(page,info,"second-delete-admitted",{deletes,requests});await expect(page.locator('.workspace-heading [data-policy-draft]')).toHaveAttribute("data-policy-draft","unchanged");await expect(page.locator('[data-canvas-node="fallback"]')).toContainText("default");await expect(page.getByRole("button",{name:words.canvasUndo,exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:words.canvasRedo,exact:true})).toBeDisabled();expect(mockApi.canvasLayout).toEqual(saved);expect(requests.filter(r=>r.path===path&&r.method!=="GET")).toEqual([{method:"DELETE",path},{method:"DELETE",path}]);await capture(page,info,"native-reset-complete",{deletes,requests,saved,current:mockApi.canvasLayout});
});

test("final obsolete ApiError 401 settles during a newer busy validation",async({page,mockApi},info)=>{
  mockApi.canvasLayout=structuredClone(layout);mockApi.appliedConfiguration={...structuredClone(configuration),config_hash:"wave4-auth",fallback:{label:"quality"}};
  let deletes=0,reads=0,metas=0,obsoleteReleased=false,validations=0,releaseOld!:()=>void,releaseMeta!:()=>void,releaseValidation!:()=>void;const old=new Promise<void>(r=>releaseOld=r),meta=new Promise<void>(r=>releaseMeta=r),validation=new Promise<void>(r=>releaseValidation=r);const requests:{method:string;path:string}[]=[],responses:{status:number;body:unknown}[]=[];
  const responseReads:{status:number;done:Promise<void>}[]=[];
  page.on("request",r=>requests.push({method:r.method(),path:new URL(r.url()).pathname}));page.on("response",r=>{if(new URL(r.url()).pathname===path)responseReads.push({status:r.status(),done:(async()=>{responses.push({status:r.status(),body:await r.json().catch(()=>null)});})()});});
  await page.route("**/v1/routing/strategies",async route=>{if(++metas===2){await meta;return route.fulfill({status:401,json:{error:{message:"Current suspension"}}});}return route.fallback();});
  await page.route(`**${path}`,async route=>{if(route.request().method()==="DELETE"){deletes++;mockApi.appliedConfiguration=undefined;mockApi.configurationApplied=false;return route.abort("failed");}if(route.request().method()==="GET"&&deletes){const n=++reads;if(n===1){await old;return route.fulfill({status:401,json:{error:{message:"Old first 401"}}});}if(obsoleteReleased)return route.fulfill({status:401,json:{error:{message:"Old final ApiError 401",code:"obsolete_final_401"}}});}return route.fallback();});
  await page.route("**/v1/routing/configuration/validate",async route=>{validations++;await validation;return route.fulfill({json:{valid:true,warnings:[]}});});
  const words=await open(page,"en",1280,"dark");await page.getByRole("button",{name:words.resetBaseline,exact:true}).click();await page.getByRole("button",{name:words.confirmReset,exact:true}).click();await page.getByRole("button",{name:words.routingRetryRead,exact:true}).click();await expect.poll(()=>reads).toBe(1);releaseMeta();await expect(page.locator("#gateway-api-key")).toBeVisible();await page.locator("#gateway-api-key").fill("synthetic-wave4-key");await page.getByRole("button",{name:words.connect,exact:true}).click();await expect(page.locator("[data-connection-page]")).toHaveCount(0);await page.getByRole("button",{name:words.routingRetryRead,exact:true}).click();await expect(page.locator('[data-canvas-node="fallback"]')).toContainText("default");
  await page.locator('[data-canvas-node="questions"]').click();const field=page.getByRole("complementary",{name:words.nodeInspector}).getByRole("textbox",{name:words.instructions,exact:true});const raw="Newer owner retains 原始 instructions";await field.fill(raw);await page.getByRole("button",{name:words.closeInspector,exact:true}).click();await page.getByRole("button",{name:words.reviewChanges,exact:true}).click();await expect(page.getByRole("button",{name:words.canvasAddNode,exact:true})).toBeDisabled();
  await expect.poll(()=>validations).toBe(1);const readsBefore=reads;await capture(page,info,"new-validation-admitted",{readsBefore,validations,requests});
  const last=page.waitForResponse(async r=>r.url().endsWith(path)&&r.status()===401&&(await r.json()).error?.code==="obsolete_final_401");obsoleteReleased=true;releaseOld();const response=await last;await response.finished();await expect.poll(()=>reads).toBe(readsBefore+1);await frames(page);await frames(page);
  expect(responseReads.filter(r=>r.status===401)).toHaveLength(2);await Promise.all(responseReads.map(r=>r.done));
  expect(responses.filter(r=>r.status===401)).toHaveLength(2);await expect(page.locator("[data-connection-page]")).toHaveCount(0);await expect(page.getByRole("alert")).toHaveCount(0);await expect(page.getByRole("button",{name:words.canvasAddNode,exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:words.settings,exact:true})).toBeDisabled();expect(deletes).toBe(1);expect(requests.filter(r=>r.path===path&&r.method!=="GET")).toEqual([{method:"DELETE",path}]);await capture(page,info,"obsolete-error-settled-new-owner-busy",{reads,deletes,responses,requests});
  releaseValidation();await expect(page.getByRole("button",{name:words.confirmAndSave,exact:true})).toBeEnabled();await page.getByRole("button",{name:words.backToEditing,exact:true}).click();await page.locator('[data-canvas-node="questions"]').click();await expect(field).toHaveValue(raw);expect(mockApi.canvasLayout?.nodes).toEqual(layout.nodes);expect(reads).toBe(readsBefore+1);await capture(page,info,"new-owner-completed",{readsBefore,reads,deletes,responses,requests,raw});
});

for(const [mode,locale,width,scheme] of [["readonly","en",320,"dark"],["readonly","zh-CN",390,"light"],["recovery","en",390,"light"],["recovery","zh-CN",320,"dark"]] as const)test(`native wheel exposes inspector fields ${mode} ${locale} ${width} ${scheme}`,async({page,mockApi},info)=>{
  mockApi.canvasLayout=structuredClone(layout);mockApi.appliedConfiguration={...structuredClone(configuration),config_hash:"wave4-scroll",write_available:mode!=="readonly",fallback:{label:"quality"}};let deletes=0;const requests:{method:string;path:string}[]=[];page.on("request",r=>requests.push({method:r.method(),path:new URL(r.url()).pathname}));
  await page.setViewportSize({width,height:900});await page.emulateMedia({colorScheme:scheme,reducedMotion:"reduce"});await page.goto("/dashboard/");if(locale==="zh-CN"){await page.getByRole("button",{name:en.settings,exact:true}).click();await page.locator("[data-settings-language]").selectOption(locale);}const words=locale==="en"?en:zhCN;await page.getByRole("button",{name:words.strategyEditor,exact:true}).click();await expect(page.locator('[data-canvas-node="questions"]')).toBeVisible();await tab(page,page.locator('[data-canvas-node="questions"]'));await page.keyboard.press("Enter");const inspector=page.getByRole("complementary",{name:words.nodeInspector}),field=inspector.getByRole("textbox",{name:words.instructions,exact:true}),newQuestion=inspector.getByRole("textbox",{name:words.newQuestion,exact:true});let raw=configuration.questions.intent!.instructions;
  if(mode==="recovery"){raw="Wheel retains 原始 inputs";await field.fill(raw);await newQuestion.fill("Unfinished 问题");await page.getByRole("button",{name:words.closeInspector,exact:true}).click();await page.route(`**${path}`,async route=>{if(route.request().method()==="DELETE"){deletes++;return route.abort("failed");}return route.fallback();});await page.getByRole("button",{name:words.resetBaseline,exact:true}).click();await page.getByRole("button",{name:words.confirmReset,exact:true}).click();await expect(page.getByRole("button",{name:words.routingRetryRead,exact:true})).toBeEnabled();const information=page.getByRole("button",{name:words.canvasInformation,exact:true});if(await information.getAttribute("aria-expanded")==="true"){await tab(page,information);await page.keyboard.press("Enter");}await tab(page,page.locator('[data-canvas-node="questions"]'));await page.keyboard.press("Enter");}
  await expect(field).toBeDisabled();const before=await bounds(field),writesBeforeScroll=structuredClone(requests.filter(r=>r.method!=="GET")),savedBeforeScroll=structuredClone(mockApi.canvasLayout);expect(savedBeforeScroll?.nodes).toEqual(layout.nodes);await capture(page,info,"before-user-scroll",{before,requests,deletes,writesBeforeScroll,savedBeforeScroll});
  const scroll=async(target:Locator,stage:string)=>{for(let n=0;n<12;n++){const b=await bounds(target);if(b.hits.every(Boolean)&&b.rect.top>=0&&b.rect.bottom<=900)break;const box=await inspector.boundingBox();expect(box).not.toBeNull();await page.mouse.move(box!.x+box!.width/2,box!.y+Math.min(box!.height-30,110));await page.mouse.wheel(0,220);await frames(page);}const b=await bounds(target);expect(b.hits.every(Boolean),JSON.stringify(b)).toBe(true);await capture(page,info,stage,{bounds:b,value:await target.inputValue(),requests,deletes});return b;};
  await scroll(field,"instructions-after-native-wheel");await expect(field).toHaveValue(raw);await scroll(newQuestion,"footer-field-after-native-wheel");await expect(newQuestion).toHaveValue(mode==="recovery"?"Unfinished 问题":"");const close=page.getByRole("button",{name:words.closeInspector,exact:true});const focus=await tab(page,close);await page.keyboard.press("Enter");await expect(inspector).toHaveCount(0);expect(requests.filter(r=>r.method!=="GET")).toEqual(writesBeforeScroll);expect(writesBeforeScroll.filter(r=>r.path===path)).toEqual(mode==="recovery"?[{method:"DELETE",path}]:[]);expect(mockApi.canvasLayout).toEqual(savedBeforeScroll);await capture(page,info,"closed-after-native-scroll",{focus,requests,deletes,writesBeforeScroll,savedBeforeScroll});
});
