import { test, expect } from "../fixtures/provider-browser";
import { configuredModelEdit, openProviderModels } from "../fixtures/open-provider-models";
import { installProviderFixture, providerFixture } from "../fixtures/provider-management";
import type { ProviderFixtureState } from "../fixtures/provider-management";

for (const owned of [[], ["tags"], ["priority"], ["tags", "priority"]] as Array<Array<"tags" | "priority">>) test(`model ownership ${owned.join(",") || "baseline"}`, async ({ page, context }) => {
  const configuration = providerFixture();
  configuration.models[0]!.routing_overlay_fields = [...owned];
  configuration.models[0]!.priority = -7;
  const state: ProviderFixtureState = { configuration, writes: [], validations: [], selectors: [] };
  await installProviderFixture(context, state);
  await page.goto("/dashboard/");
  await openProviderModels(page, "fixture");
  await configuredModelEdit(page, "fixture", "existing").click();
  const dialog = page.getByRole("dialog");
  const tags = dialog.getByLabel("Routing tags (comma separated)", { exact: true });
  const priority = dialog.getByLabel("Priority", { exact: true });
  expect(await tags.getAttribute("readonly") !== null).toBe(owned.includes("tags"));
  expect(await priority.getAttribute("readonly") !== null).toBe(owned.includes("priority"));
  if (!owned.includes("tags")) await tags.fill("baseline-tag");
  if (!owned.includes("priority")) await priority.fill("-9");
  await dialog.getByRole("button", { name: "Save", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const operation = state.writes[0]!.operations[0]!;
  expect(operation.action).toBe("update_model");
  if (operation.action !== "update_model") throw new Error("Expected model update");
  for (const field of owned) expect(operation.model).not.toHaveProperty(field);
  if (!owned.includes("tags")) expect(operation.model.tags).toEqual(["baseline-tag"]);
  if (!owned.includes("priority")) expect(operation.model.priority).toBe(-9);
});

test("conflict ownership reload retains drafts and requires explicit field reconciliation", async ({ page, context }) => {
  const configuration = providerFixture(); configuration.models[0]!.routing_overlay_fields = [];
  const state: ProviderFixtureState = { configuration, writes: [], validations: [], selectors: [] };
  await installProviderFixture(context, state); await page.goto("/dashboard/");
  await openProviderModels(page, "fixture");
  await configuredModelEdit(page, "fixture", "existing").click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Routing tags (comma separated)", { exact: true }).fill("attempted-tag");
  await dialog.getByLabel("Priority", { exact: true }).fill("-9");
  await dialog.getByLabel("Display name", { exact: true }).fill("Retained name");
  state.rejectWrite = 409;
  await dialog.getByRole("button", { name: "Save", exact: true }).click();
  configuration.models[0]!.routing_overlay_fields = ["tags"];
  configuration.models[0]!.tags = ["workflow-tag"];
  await dialog.getByRole("button", { name: "Reload current configuration", exact: true }).click();
  await expect(dialog.getByLabel("Routing tags (comma separated)", { exact: true })).toHaveValue("attempted-tag");
  await expect(dialog.getByRole("button", { name: "Save", exact: true })).toBeDisabled();
  await dialog.getByRole("button", { name: "Use current workflow values", exact: true }).click();
  await expect(dialog.getByLabel("Routing tags (comma separated)", { exact: true })).toHaveValue("workflow-tag");
  await expect(dialog.getByLabel("Priority", { exact: true })).toHaveValue("-9");
  await expect(dialog.getByLabel("Display name", { exact: true })).toHaveValue("Retained name");
  await dialog.getByRole("button", { name: "Save", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect(state.writes[1]!.operations[0]).toMatchObject({ model: { display_name: "Retained name", priority: -9 } });
  expect((state.writes[1]!.operations[0] as { model: object }).model).not.toHaveProperty("tags");
});

test("restore preview permits same-value manual to source ownership", async ({ page, context }) => {
  const configuration = providerFixture();
  configuration.models[0]!.routing_overlay_fields = [];
  configuration.models[0]!.cost.input_per_million = 1.5;
  configuration.models[0]!.metadata = { version: 1, fields: { input_per_million: { status: "confirmed", value: 1.5, method: "manual" } } };
  const state: ProviderFixtureState = { configuration, writes: [], validations: [], selectors: [] };
  await installProviderFixture(context, state); await page.goto("/dashboard/");
  await openProviderModels(page, "fixture");
  await configuredModelEdit(page, "fixture", "existing").click();
  const dialog = page.getByRole("dialog");
  await dialog.getByRole("button", { name: "Refresh metadata sources", exact: true }).click();
  await expect.poll(() => state.metadataCalls).toBe(1);
  await dialog.getByRole("button", { name: "Restore automatic values", exact: true }).click();
  await dialog.getByText("Input price (USD / million tokens): 1.5 → 1.5 (Manual → source)", { exact: true }).check();
  await dialog.getByRole("button", { name: "Apply selected values", exact: true }).click();
  await dialog.getByRole("button", { name: "Save", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect(configuration.models[0]!.cost.input_per_million).toBe(1.5);
  expect(configuration.models[0]!.metadata?.fields?.input_per_million?.method).toBe("source");
  expect(configuration.models[0]!.metadata?.sources?.length).toBeGreaterThan(0);
});
